#!/bin/bash

function validate_name() {
    if [[ $1 =~ ^[a-zA-Z][a-zA-Z0-9_]*$ ]]; then
        return 0
    else
        return 1
    fi
}

function validate_datatype() {
    case $1 in
        "string"|"integer"|"float") return 0 ;;
        *) return 1 ;;
    esac
}

function validate_value() {
    local value=$1
    local datatype=$2
    
    case $datatype in
        "string") return 0 ;;
        "integer") 
            if [[ $value =~ ^[0-9]+$ ]]; then
                return 0
            else
                return 1
            fi ;;
        "float")
            if [[ $value =~ ^[0-9]+\.[0-9]+$ ]]; then
                return 0
            else
                return 1
            fi ;;
    esac
}

function check_duplicate_key() {
    local table=$1
    local pk_value=$2
    local pk_index=$3
    
    # Skip header line and check each record
    while IFS='|' read -r line; do
        local values=($line)
        if [ "${values[$pk_index]}" == "$pk_value" ]; then
            return 0 # Found duplicate
        fi
    done < <(tail -n +2 "$DB_DIR/$CURRENT_DB/$table")
    return 1 # No duplicate found
}
