#!/bin/bash
source ./src/config.sh
source ./src/utils/menu.sh
source ./src/utils/validators.sh
source ./src/operations/database.sh
source ./src/operations/table.sh
source ./src/operations/record.sh

main_menu